// =======================
// Auth / Login Actions
// =======================
export const LOGIN_START = "LOGIN_START";
export const LOGIN_SUCCEEDED = "LOGIN_SUCCEEDED";
export const LOGIN_FAILED = "LOGIN_FAILED";
export const LOGOUT = "LOGOUT";

// =======================
// User Actions
// =======================
export const FETCH_USER_START = "FETCH_USER_START";
export const FETCH_USER_SUCCEEDED = "FETCH_USER_SUCCEEDED";
export const FETCH_USER_FAILED = "FETCH_USER_FAILED";

export const REGISTER_USER_START = "REGISTER_USER_START";
export const REGISTER_USER_SUCCEEDED = "REGISTER_USER_SUCCEEDED";
export const REGISTER_USER_FAILED = "REGISTER_USER_FAILED";

// =======================
// Employee Actions
// =======================
export const FETCH_EMPLOYEES_START = "FETCH_EMPLOYEES_START";
export const FETCH_EMPLOYEES_SUCCEEDED = "FETCH_EMPLOYEES_SUCCEEDED";
export const FETCH_EMPLOYEES_FAILED = "FETCH_EMPLOYEES_FAILED";

export const CREATE_EMPLOYEE_START = "CREATE_EMPLOYEE_START";
export const CREATE_EMPLOYEE_SUCCEEDED = "CREATE_EMPLOYEE_SUCCEEDED";
export const CREATE_EMPLOYEE_FAILED = "CREATE_EMPLOYEE_FAILED";

export const UPDATE_EMPLOYEE_START = "UPDATE_EMPLOYEE_START";
export const UPDATE_EMPLOYEE_SUCCEEDED = "UPDATE_EMPLOYEE_SUCCEEDED";
export const UPDATE_EMPLOYEE_FAILED = "UPDATE_EMPLOYEE_FAILED";

export const DELETE_EMPLOYEE_START = "DELETE_EMPLOYEE_START";
export const DELETE_EMPLOYEE_SUCCEEDED = "DELETE_EMPLOYEE_SUCCEEDED";
export const DELETE_EMPLOYEE_FAILED = "DELETE_EMPLOYEE_FAILED";
